[package]
name = "license_display"
authors = ["RemasteredArch"]
readme = true
license = "MPL-2.0"
version = "0.1.0"
edition = "2024"

[dependencies]
spdx = { version = "0.10.8", features = ["text"] }
